### PR TITLE
A collection of small stories

### PR DESCRIPTION
**Pull request by pixeltrix**
See individual commits for details

### CODE REVIEW

**Comment by pixeltrix** [comment]
[Make "Background Information" a required field](https://trello.com/c/mT8KyMZH/156-make-background-information-a-required-field)

**Comment by pixeltrix** [comment]
[Submit a Paper Petition should match online submission text fields](https://trello.com/c/ZsJPaYWs/158-submit-a-paper-petition-should-match-online-submission-text-fields)

**Comment by pixeltrix** [comment]
[Hide "Special Consideration" in Back End](https://trello.com/c/tVNp7EfV/119-hide-special-consideration-in-back-end)

**Comment by pixeltrix** [comment]
[Hide "Committee Notes" in Back End](https://trello.com/c/wMY3PidC/118-hide-committee-notes-in-back-end)

**Comment by pixeltrix** [comment]
[Backend "Update ABMS link" to read "ScotParl Weblink"](https://trello.com/c/pVBcIWrK/139-backend-update-abms-link-to-read-scotparl-weblink)

**Review by freesteph — APPROVED** [review]

**Pull request merged**
