### PR TITLE
Update README to say "scotspets" not "scotpets"

### PR DESCRIPTION
**Pull request by cdccollins**

### CODE REVIEW

**Comment by pixeltrix** [comment]
What sounds better `scotspets` or `scotpets`? ScotsPets fells awkward to say and Scots is an actual language so worried about some confusion there.

**Comment by cdccollins** [comment]
> What sounds better `scotspets` or `scotpets`? ScotsPets fells awkward to say and Scots is an actual language so worried about some confusion there.

If we want to go with `scotpets` we'll have to do some changes to the app itself, so I thought just changing the README was the easier option 😂

**Comment by pixeltrix** [comment]
[Change README to scotspets](https://trello.com/c/osXbb8YN/63-change-readme-to-scotspets)

**Comment by pixeltrix** [comment]
[Change README to scotspets](https://trello.com/c/osXbb8YN/63-change-readme-to-scotspets)

**Review by freesteph — APPROVED** [review]

**Pull request merged**
